
// Let firmware know that rgb leds are not soldered
#define RGB_LEDS_NOT_SOLDERED

#include "keymap_common.h"

const uint8_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  // layer 0: space fn
  KEYMAP_ERGO(
      ESC,      F1,  F2,  F3,  F4,  F5,     F6,  F7,  F8,  F9,  F10, F11, F12,         PSCR,SLCK,PAUS,
      FN0, 1,   2,   3,   4,   5,   6,      7,   8,   9,   0,   MINS,EQL, NO,  BSPC,   INS, HOME,PGUP,
      TAB, Q,   W,   E,   R,   T,           Y,   U,   I,   O,   P,   LBRC,RBRC,BSLS,   DEL, END, PGDN,
      FN1, A,   S,   D,   F,   G,           H,   J,   K,   L,   SCLN,QUOT,NO,  ENT,
      LSFT,NO,  Z,   X,   C,   V,   B,      FN1, N,   M,   COMM,DOT, SLSH,RSFT,             UP,
      LCTL,APP, LGUI,LALT,          FN2,    FN2,           FN3, RGUI,APP, RCTL,        LEFT,DOWN,RGHT),
  // layer 1: gaming
  KEYMAP_ERGO(
      TRNS,     TRNS,TRNS,TRNS,TRNS,TRNS,   TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,        TRNS,TRNS,TRNS,
      GRV, TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,   TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO,  TRNS,   TRNS,TRNS,TRNS,
      TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,   TRNS,TRNS,TRNS,
      FN4, TRNS,TRNS,TRNS,TRNS,TRNS,        TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO,  TRNS,
      TRNS,NO,  TRNS,TRNS,TRNS,TRNS,TRNS,   TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,             TRNS,
      TRNS,NO,  NO,  TRNS,          SPC,    SPC,           TRNS,NO,  NO,  TRNS,        TRNS,TRNS,TRNS),
  // layer 2: first function layer
  KEYMAP_ERGO(
      TRNS,     TRNS,TRNS,TRNS,TRNS,TRNS,   TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,        TRNS,TRNS,TRNS,
      FN5, FN6, TRNS,TRNS,TRNS,TRNS,TRNS,   TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO,  TRNS,   TRNS,TRNS,TRNS,
      TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,        WBAK,WH_D,WH_U,WFWD,TRNS,TRNS,TRNS,TRNS,   TRNS,TRNS,TRNS,
      TRNS,ACL0,ACL1,ACL2,TRNS,TRNS,        MS_L,MS_D,MS_U,MS_R,TRNS,TRNS,NO,  TRNS,
      TRNS,NO,  TRNS,TRNS,TRNS,BTN3,BTN2,   TRNS,BTN1,BTN4,BTN5,TRNS,TRNS,TRNS,             TRNS,
      TRNS,TRNS,TRNS,TRNS,          BTN1,   BTN1,          TRNS,TRNS,TRNS,TRNS,        TRNS,TRNS,TRNS),
  // layer 3: second function layer
  KEYMAP_ERGO(
      TRNS,     TRNS,TRNS,TRNS,TRNS,TRNS,   TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,        TRNS,TRNS,TRNS,
      GRV, TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,   TRNS,TRNS,TRNS,TRNS,TRNS,TRNS,NO,  PGUP,   TRNS,TRNS,TRNS,
      TRNS,TRNS,Y,   P,   PSCR,SLCK,        PAUS,HOME,INS, DEL, END, TRNS,TRNS,PGDN,   TRNS,TRNS,TRNS,
      CAPS,M,   TRNS,5,   TRNS,TRNS,        LEFT,DOWN,UP,  RGHT,TRNS,TRNS,NO,  TRNS,
      TRNS,NO,  TRNS,TRNS,TRNS,TRNS,TRNS,   TRNS,FN7, TRNS,TRNS,TRNS,TRNS,TRNS,             TRNS,
      TRNS,TRNS,TRNS,TRNS,          TRNS,   TRNS,          TRNS,TRNS,TRNS,TRNS,        TRNS,TRNS,TRNS)
};

enum LayerId {
  LAYER_SPACEFN,
  LAYER_GAMING,
  LAYER_FUNCTIONS_FIRST,
  LAYER_FUNCTIONS_SECOND
};

const action_t fn_actions[] PROGMEM = {
  [0] = ACTION_MODS_KEY(MOD_RSFT, KC_GRV),
  [1] = ACTION_LAYER_TAP_KEY(LAYER_FUNCTIONS_FIRST, KC_ESC),
  [2] = ACTION_LAYER_TAP_KEY(LAYER_FUNCTIONS_SECOND, KC_SPACE),
  [3] = ACTION_LAYER_MODS(LAYER_FUNCTIONS_SECOND, MOD_RALT),
  [4] = ACTION_LAYER_TAP_KEY(LAYER_FUNCTIONS_FIRST, KC_CAPS),
  [5] = ACTION_LAYER_TOGGLE(LAYER_GAMING),
  [6] = ACTION_BACKLIGHT_LEVEL(BACKLIGHT_SWITCH),
  [7] = ACTION_MODS_KEY(MOD_LSFT, KC_INS)
};
